 CREATE TABLE USER ( USER_ID INT NOT NULL AUTO_INCREMENT, 
    USERNAME varchar(255), 
    EMAIL varchar(255),
    PASSWORD varchar(255), 
    SALT varchar(255), 
    DATE_DER_CO DATE, 
    PRIMARY KEY(USER_ID));


CREATE TABLE SENTENCE ( 
    SENTENCE_ID INT NOT NULL AUTO_INCREMENT, 
    SENTENCE varchar(255),
    LANG varchar(5),
    FOREIGN KEY (LANG) REFERENCES LANG(LANG),
    PRIMARY KEY(SENTENCE_ID)); 


CREATE TABLE TRANSLATE( 
    ORIGIN_ID INT,
    TRANSLATED_ID INT,
    FOREIGN KEY (ORIGIN_ID) REFERENCES SENTENCE(SENTENCE_ID),
    FOREIGN KEY (TRANSLATED_ID) REFERENCES SENTENCE(SENTENCE_ID));

CREATE TABLE LANG (
    LANG varchar(5),
    NAME varchar(40),
    PRIMARY KEY(LANG));


    SELECT SENTENCE FROM SENTENCE where LANG = "en.UK" and SENTENCE_ID = 
    (SELECT TRANSLATE.TRANSLATED_ID FROM TRANSLATE WHERE TRANSLATE.ORIGIN_ID= 
    (SELECT SENTENCE_ID FROM SENTENCE WHERE SENTENCE.SENTENCE = "bonjour"));
