 CREATE TABLE USER ( USER_ID INT NOT NULL AUTO_INCREMENT, 
    USERNAME varchar(255), 
    EMAIL varchar(255),
    PASSWORD varchar(255), 
    SALT varchar(255), 
    DATE_DER_CO DATE, 
    PRIMARY KEY(USER_ID));


CREATE TABLE WORD ( WORD_ID INT NOT NULL AUTO_INCREMENT, 
    WORD varchar(255),
    LANG varchar(4),
    PRIMARY KEY(WORD_ID));

CREATE TABLE TRADUCTION( 
    TRAD_ID INT NOT NULL AUTO_INCREMENT,
    FIRST_WORD_ID FOREIGN KEY REFERENCES WORD(WORD_ID),
    SECOND_WORD_ID FOREIGN KEY REFERENCES WORD(WORD_ID),
    PRIMARY KEY(TRAD_ID)
);

